# Generated by Django 3.2.6 on 2021-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_field', models.CharField(max_length=100)),
                ('text_author', models.TextField()),
                ('create_data', models.DateField()),
                ('create_update', models.DateField()),
            ],
        ),
    ]
