# Generated by Django 3.2.6 on 2021-08-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create_data',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='create_update',
            new_name='update_date',
        ),
    ]
