# Generated by Django 3.2.6 on 2021-08-18 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_auto_20210818_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 8, 18)),
        ),
        migrations.AlterField(
            model_name='message',
            name='update_date',
            field=models.DateField(default=datetime.date(2021, 8, 18)),
        ),
    ]
